
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: MacMini

development:
  <<: *default
  database: TravelItinerary_development


test:
  <<: *default
  database: TravelItinerary_test

production:
  <<: *default
  database: TravelItinerary_production
  username: TravelItinerary
  password: <%= ENV['TRAVELITINERARY_DATABASE_PASSWORD'] %>
